### PR TITLE
bugfix: No response when open a file with jdt uri

### LINKED ISSUE #219: Right click on folder under jar doesn't work
#### Configuration:
```
VScode: 1.41.1
JDK: 1.8.0_231
OS: Win
Java Dependency view version: 0.7.0
Language Support for Java version:0.55.1
```

#### Repro Steps:
1. Open a project in vscode
2. Open java dependecies viewer, 
3. Right click the file under folder and click "reveal in explorer" 
image

#### Result:
Right click on a folder under .jar, it doesn't work.
Right click on a file under the folder in .jar, "Reveal in Explorer" doesn't work

### PR DESCRIPTION
**Pull request by jdneo**
fix #219

### CODE REVIEW

File: src/views/dataNode.ts [hunk 1]
```diff
@@ -58,7 +58,7 @@ export abstract class DataNode extends ExplorerNode {
 
     protected computeContextValue(): string {
         let contextValue = this.contextValue;
-        if (this.uri) {
+        if (this.uri && this.uri.startsWith("file")) {
```
Comment (testforstephen) [inline src/views/dataNode.ts]: startsWith("file:")?

Comment (jdneo) [reply src/views/dataNode.ts]: Yes that's better
