### PR TITLE
fix: NPE error when open non-project file

### LINKED ISSUE #418: NPE error when open non-project file
When we open a non-java file which doesn't belong to the opened project (e.g. execute `Java: Open Java Language Server Log`), LS will throw NPE error like below:

image
image

### PR DESCRIPTION
**Pull request by xqzlgy2**
When we open a non-java file which doesn't belong to the opened project, LS will throw NPE error, since in `resolvePath` api we assume the file should be in workspace. So, additional checks are needed.

fix #418

### CODE REVIEW

**Comment by jdneo** [comment]
I think you can check this case at the client side in order to save the traffic to the language server: https://github.com/microsoft/vscode-java-dependency/blob/master/src/views/dependencyExplorer.ts#L49

Also please create a new issue for this bug for easy tracking.

Thanks.

File: src/views/dependencyExplorer.ts [hunk 1]
```diff
@@ -48,6 +48,10 @@ export class DependencyExplorer implements Disposable {
             window.onDidChangeActiveTextEditor((textEditor: TextEditor) => {
                 if (this._dependencyViewer.visible && textEditor && textEditor.document && Settings.syncWithFolderExplorer()) {
                     const uri: Uri = textEditor.document.uri;
+                    // if editor doesn't belong to workspace, do nothing
+                    if (uri.fsPath === workspace.asRelativePath(uri.fsPath)) {
```
Comment (jdneo) [inline src/views/dependencyExplorer.ts:52]: Using `workspace.getWorkspaceFolder()` is more readable IMO

**Review by jdneo — APPROVED** [review]
