### PR TITLE
fix: Make export jar task unblock fetch task process

### LINKED ISSUE #720: I cannot open build tasks by ctrl+shift+b because of this extension
Type: <b>Bug</b>

turn on this extension and use hotkeys to bring up the task menu, it will stuck at the 'Fetching Tasks' phase.

Extension version: 0.21.1
VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 6, 5|
|Memory (System)|16.00GB (2.63GB free)|
|Process Argv|--crash-reporter-id d2743afe-0b94-4c78-b00e-97554cafa983|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30669238
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsctsb:30662444
pythonb192:30669360

```

</details>

### PR DESCRIPTION
**Pull request by CsCherrYY**
fix #720 

This PR contains two things:

- catch potential exceptions when sending request to jdtls
- wait 1s at most when getting the language server status. Once timeout, will directly return original task (when resolving tasks) or undefined (when providing tasks)

### CODE REVIEW

File: src/tasks/buildArtifact/BuildArtifactTaskProvider.ts [hunk 1]
```diff
@@ -134,44 +141,52 @@ export class BuildArtifactTaskProvider implements TaskProvider {
...
-                    };
-                    return new ExportJarTaskTerminal(resolvedDefinition, stepMetadata);
-                }), undefined);
-            defaultTask.presentationOptions.reveal = TaskRevealKind.Never;
-            this.tasks.push(defaultTask);
         }
         return this.tasks;
     }
+
+    private static getLanguageServerStatusTimeout(): Promise<boolean> {
```
Comment (jdneo) [inline src/tasks/buildArtifact/BuildArtifactTaskProvider.ts:187]: nit: just calling it `languageServerStatusTimeout()` should be fine. Since we do not get some real data here

File: src/tasks/buildArtifact/BuildArtifactTaskProvider.ts [hunk 2]
```diff
@@ -99,30 +99,37 @@ export class BuildArtifactTaskProvider implements TaskProvider {
...
+            resolvedTask.presentationOptions.reveal = TaskRevealKind.Never;
+            return resolvedTask;
+        } catch (e) {
+            return task;
+        }
     }
 
     public async provideTasks(): Promise<Task[] | undefined> {
-        if (!await languageServerApiManager.ready()) {
+        const languageServerStatus = await Promise.race([languageServerApiManager.ready(), BuildArtifactTaskProvider.getLanguageServerStatusTimeout()]);
```
Comment (jdneo) [inline src/tasks/buildArtifact/BuildArtifactTaskProvider.ts:131]: And let's extract this Promise.race statement to a method with document explaining the reason doing this.

Comment (CsCherrYY) [reply src/tasks/buildArtifact/BuildArtifactTaskProvider.ts]: in https://github.com/microsoft/vscode-java-dependency/pull/722/commits/0f4564ca738ba542897b646f97219d1f8cc32608 we:

1. extract the utility to languageServerApiManager, named `isReady(timeout)`
2. rename original `isReady` field to `isServerReady`

**Review by jdneo — APPROVED** [review]
LGTM!
