### PR TITLE
fix: Exporting Jar lasts all time in unmanaged folders

### LINKED ISSUE #419: Exporting Jar lasts all time.
Environment:

OS: Win 10
Vscode: 1.52.0
Vscode java project manager: 0.16.0

Actual:

Exporting Jar lasts all time.(just for no build tools project)
image

### PR DESCRIPTION
**Pull request by CsCherrYY**
Fix #419

### CODE REVIEW

File: src/exportJarSteps/GenerateJarExecutor.ts [hunk 1]
```diff
@@ -115,11 +115,18 @@ export class GenerateJarExecutor implements IExportJarStepExecutor {
                     return reject(new Error(ExportJarMessages.fieldUndefinedMessage(ExportJarMessages.Field.WORKSPACEFOLDER, this.currentStep)));
                 }
                 for (const project of projectList) {
-                    const classpaths: IClasspathResult = await extensionApi.getClasspaths(project.uri, { scope: "runtime" });
+                    const classpath: string = (project.metaData?.UnmanagedFolderInnerPath) ? project.metaData.UnmanagedFolderInnerPath : project.uri;
```
Comment (jdneo) [inline src/exportJarSteps/GenerateJarExecutor.ts:118]: `const projectUri = project.metaData?.UnmanagedFolderInnerPath || project.uri`

**Review by jdneo — CHANGES_REQUESTED** [review]

**Review by jdneo — APPROVED** [review]
