### PR TITLE
fix: Add eol after emitting export jar end message

### LINKED ISSUE #699: Output of the exporting jar task can be improved
image

create a new line at the end of the task

### PR DESCRIPTION
**Pull request by CsCherrYY**
fix #699

### CODE REVIEW

File: src/tasks/buildArtifact/BuildArtifactTaskProvider.ts [hunk 1]
```diff
@@ -206,7 +206,7 @@ class ExportJarTaskTerminal implements Pseudoterminal {
 
     public exit(message?: string) {
         if (message) {
-            this.writeEmitter.fire(message);
+            this.writeEmitter.fire(message + "\r\n");
```
Comment (jdneo) [inline src/tasks/buildArtifact/BuildArtifactTaskProvider.ts:209]: If `message` is undefined, will the output look good?

Comment (CsCherrYY) [reply src/tasks/buildArtifact/BuildArtifactTaskProvider.ts:209]: if message is undefined, we will not invoke writeEmitter so nothing will happen in the outout panel.

**Review by jdneo — APPROVED** [review]
