### PR TITLE
fix: Prevent multiple calls of reveal() at the same time

### LINKED ISSUE #400: Duplicated items show in the explorer
image

This is commonly observed when multiple calls for the `reveal()` happens then the view will be rendered repeatedly. We need to find a way to eliminate the duplicated calls

### PR DESCRIPTION
**Pull request by jdneo**
fix #400

### CODE REVIEW

File: src/views/dependencyExplorer.ts [hunk 1]
```diff
@@ -137,17 +140,28 @@ export class DependencyExplorer implements Disposable {
...
             const paths: INodeData[] = await Jdtls.resolvePath(uri.toString());
-            if (!paths || paths.length === 0) {
-                return;
+            if (!_.isEmpty(paths)) {
+                node = await this._dataProvider.revealPaths(paths);
             }
-            node = await this._dataProvider.revealPaths(paths);
         }
 
-        if (this._dependencyViewer.visible) {
```
Comment (CsCherrYY) [inline src/views/dependencyExplorer.ts:149]: Is `this._dependencyViewer.visible` will be always `ture`? Or it should not be a condition for `reveal`?

Comment (jdneo) [reply src/views/dependencyExplorer.ts:149]: According to the document for the `reveal()` API:

> Reveals the given element in the tree view. If the tree view is not visible then the tree view is shown and element is revealed.

**Review by CsCherrYY — APPROVED** [review]
